### ISSUE TITLE
scEpath R package

### ISSUE THREAD

**Issue by CodeInTheSkies** [sqjin/scEpath#2]
Hello there,

scEpath looks like a really nice package to go hand-in-hand with a psuedotime package like Monocle 2.  I came across your package while reading a recent paper:

https://www.nature.com/articles/s41467-018-08247-x

I'm really interested in trying out scEpath for my data.  However, since the package is in Matlab, it seems hard to try out quickly, as I'm hesitant that it may not integrate well with the rest of my R-based single-cell pipeline.

By any chance, is this available in R?  Or, do you plan to bring it out in R anytime soon?

Thanks!

**Comment by sqjin** [comment]
Hello,

Thanks for the interest. Somehow I did not receive the notifications of the reported issues. Currently it is only available in Matlab. I was also thinking about the implementation in R. 

Best,
Suoqin
